sudo: false
dist: precise
language: ruby
cache: bundler
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
env:
  - DB=postgres ORM=active_record RAILS_VERSION=4.2
  - DB=mysql ORM=active_record RAILS_VERSION=4.2
  - DB=sqlite3 ORM=active_record RAILS_VERSION=4.2
  - DB=postgres ORM=active_record RAILS_VERSION=5.0
  - DB=mysql ORM=active_record RAILS_VERSION=5.0
  - DB=sqlite3 ORM=active_record RAILS_VERSION=5.0
  - DB=postgres ORM=active_record RAILS_VERSION=5.1
  - DB=mysql ORM=active_record RAILS_VERSION=5.1
  - DB=sqlite3 ORM=active_record RAILS_VERSION=5.1
  - DB=postgres ORM=active_record RAILS_VERSION=latest
  - DB=mysql ORM=active_record RAILS_VERSION=latest
  - DB=sqlite3 ORM=active_record RAILS_VERSION=latest
  - DB=postgres ORM=sequel SEQUEL_VERSION=4.41
  - DB=mysql ORM=sequel SEQUEL_VERSION=4.41
  - DB=sqlite3 ORM=sequel SEQUEL_VERSION=4.41
  - DB=postgres ORM=sequel SEQUEL_VERSION=4.46
  - DB=mysql ORM=sequel SEQUEL_VERSION=4.46
  - DB=sqlite3 ORM=sequel SEQUEL_VERSION=4.46
  - DB=sqlite3 ORM= TEST_PERFORMANCE=true
matrix:
  fast_finish: true
  allow_failures:
    - env: DB=postgres ORM=active_record RAILS_VERSION=latest
    - env: DB=mysql ORM=active_record RAILS_VERSION=latest
    - env: DB=sqlite3 ORM=active_record RAILS_VERSION=latest
before_script:
  - bundle exec rake db:create db:up
before_install: gem install bundler -v 1.12.5
addons:
  postgresql: "9.4"
services:
  - postgresql
